# Generated by Django 4.1.7 on 2023-04-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectmodule_endeddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Normal', 'Normal')], max_length=30),
        ),
    ]
